x-app: &app-base
    build:
        context: .
        dockerfile: .docker/app-prod/Dockerfile
    image: ghcr.io/nika39/vidium:latest
    depends_on:
        - redis
        - mysql
    networks:
        - sail
    restart: unless-stopped

services:
    app:
        <<: *app-base
        volumes:
            - app-public:/var/www/html/public

    app-octane:
        <<: *app-base
        command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=auto

    app-scheduler:
        <<: *app-base
        command: php artisan schedule:work

    web:
        build:
            context: .docker/nginx
        image: ghcr.io/nika39/vidium-web:latest
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        environment:
            - SERVER_NAME=${SERVER_NAME:-vidium.localhost}
            - SSL_DOMAIN=${SSL_DOMAIN:-vidium.localhost}
            - SSL_ALT_NAME=${SSL_ALT_NAME:-DNS:vidium.localhost}
        volumes:
            - app-public:/var/www/html/public
        depends_on:
            - app
            - app-octane
        networks:
            - sail
        restart: unless-stopped

    redis:
        image: 'redis:8-alpine'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        restart: unless-stopped

    mysql:
        image: 'mysql:9'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
            TZ: 'Asia/Tbilisi'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './.docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:5-apache
        # profiles:
        #     - tools
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            UPLOAD_LIMIT: 200M
            TZ: 'Asia/Tbilisi'
        ports:
            - '8080:80'
        networks:
            - sail
        depends_on:
            - mysql

networks:
    sail:
        driver: bridge

volumes:
    sail-redis:
        driver: local
    sail-mysql:
        driver: local
    app-public:
        driver: local
