services:
    app:
        build:
            context: './.docker/app-dev'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './.docker/app-dev/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - sail
        depends_on:
            - redis
            - mysql

    web:
        build:
            context: .docker/nginx
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '443:443'
        environment:
            - SERVER_NAME=${SERVER_NAME:-vidium.localhost}
            - SSL_DOMAIN=${SSL_DOMAIN:-vidium.localhost}
            - SSL_ALT_NAME=${SSL_ALT_NAME:-DNS:vidium.localhost}
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/templates-dev:/etc/nginx/templates
            - ./.docker/nginx/certs:/etc/nginx/certs
        depends_on:
            - app
        networks:
            - sail

    redis:
        image: 'redis:8-alpine'
        command: redis-server --maxmemory-policy allkeys-lru
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mysql:
        image: 'mysql:9'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
            TZ: 'Asia/Tbilisi'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './.docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:5-apache
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            UPLOAD_LIMIT: 200M
            TZ: 'Asia/Tbilisi'
        ports:
            - '8080:80'
        networks:
            - sail
        depends_on:
            - mysql

networks:
    sail:
        driver: bridge

volumes:
    sail-redis:
        driver: local
    sail-mysql:
        driver: local
