services:
    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        image: laravel:1.0-php8.5
        volumes:
            - app-public:/var/www/html/public
        depends_on:
            - redis
            - mysql
        networks:
            - app

    app-octane:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        image: laravel:1.0-php8.5
        command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=auto
        depends_on:
            - redis
            - mysql
        networks:
            - app

    web:
        build:
            context: .docker/nginx
        ports:
            - '80:80'
        volumes:
            - app-public:/var/www/html/public
        depends_on:
            - app
            - app-octane
        networks:
            - app

    redis:
        image: 'redis:8-alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'app-redis:/data'
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mysql:
        image: 'mysql:9'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - 'app-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:5-apache
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            UPLOAD_LIMIT: 200M
            TZ: 'Asia/Tbilisi'
        ports:
            - '8080:80'
        networks:
            - app
        depends_on:
            - mysql

networks:
    app:
        driver: bridge

volumes:
    app-redis:
        driver: local
    app-mysql:
        driver: local
    app-public:
        driver: local
